# Generated by Django 3.1.1 on 2020-12-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_sample_recognizer', '0002_auto_20201215_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiosample',
            old_name='sample',
            new_name='audio_sample_label',
        ),
    ]
