# Generated by Django 3.1.1 on 2020-12-15 15:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_sample_recognizer', '0005_auto_20201215_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosample',
            name='audio',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='raw'),
        ),
    ]
