# Generated by Django 3.1.1 on 2020-12-15 16:28

import audio_sample_recognizer.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_sample_recognizer', '0007_auto_20201215_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSampleRecognizerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=audio_sample_recognizer.models.audio_sample_model_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='audiosample',
            name='audio',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=audio_sample_recognizer.models.audio_sample_label_directory_path),
        ),
    ]
