# Generated by Django 3.1.1 on 2020-12-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_sample_recognizer', '0008_auto_20201215_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiosamplerecognizermodel',
            name='updated_at',
        ),
    ]
