# Generated by Django 3.1.1 on 2020-12-16 04:57

import audio_sample_recognizer.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_sample_recognizer', '0009_remove_audiosamplerecognizermodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosamplerecognizermodel',
            name='status_message',
            field=models.TextField(default='Model Update in progress!'),
        ),
        migrations.AddField(
            model_name='audiosamplerecognizermodel',
            name='tag',
            field=models.CharField(default='tag', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiosamplerecognizermodel',
            name='model',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=audio_sample_recognizer.models.audio_sample_model_directory_path),
        ),
    ]
