# Generated by Django 3.1.1 on 2020-12-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_sample_recognizer', '0010_auto_20201216_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosamplerecognizermodel',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
